### PR TITLE
Provide base class for dataset loaders

### PR DESCRIPTION
**Pull request by cthoyt**
# Summary
 
This PR abstracts the essential components of the dataset loader into a base class to allow for future implementations of eager datasets (e.g., all parts of the dataset are already in memory) and for other lazy local dataset loaders.
 
- [x] Code passes all tests
- [x] Unit tests provided for these changes
- [x] Documentation and docstrings added for these changes

## Changes 

* Create abstract base class with unimplemented methods for getting drugs, contexts, and labeled triples
* Rename mid-level class to `RemoteDatasetLoader`

## Next steps

The following shows an implementation of an eager dataset, which might be more useful for local datasets.

```python
@dataclass
class EagerDatasetLoader(DatasetLoader):
    """An eager dataset."""

    context_feature_set: ContextFeatureSet
    drug_feature_set: DrugFeatureSet
    labeled_triples: LabeledTriples

    def get_labeled_triples(self) -> LabeledTriples:
        """Get the labeled triples file from the storage."""
        return self.labeled_triples

    def get_context_features(self) -> ContextFeatureSet:
        """Get the context feature set."""
        return self.context_feature_set

    def get_drug_features(self):
        """Get the drug feature set."""
        return self.drug_feature_set
```

### CODE REVIEW

**Review by benedekrozemberczki — APPROVED** [review]
Looks great @cthoyt !

**Comment by aminemosbah** [comment]
any chance we would load , train and essentially test our own dataset ?

**Comment by cthoyt** [comment]
@aminemosbah I would suggest looking at https://chemicalx.readthedocs.io/en/latest/api/chemicalx.data.LocalDatasetLoader.html#chemicalx.data.LocalDatasetLoader for loading your own dataset that's already in the right format in a given directory

**Comment by aminemosbah** [comment]
thx, but i have smiles to predict in a csv file to predict locally , any quick snippet ?

**Comment by cthoyt** [comment]
@aminemosbah I have in mind a solution for what you want (which is the obvious realistic use case) but this it is blocked #50 and #58. @benedekrozemberczki would love to get your input on #50 ;)

**Comment by aminemosbah** [comment]
need to hack the dataloader to make it work for local data

**Comment by aminemosbah** [comment]
here is a possible solution 
https://chemicalx.readthedocs.io/en/latest/api/chemicalx.data.LocalDatasetLoader.html#chemicalx.data.LocalDatasetLoader

**Pull request merged**
