### PR TITLE
Adding DrugBank DDI and Two Sides.

### PR DESCRIPTION
**Pull request by benedekrozemberczki**
# Summary
 
- Adding DrugBank DDI and TwoSides.

- [X] Code passes all tests
- [X] Unit tests provided for these changes
- [X] Documentation and docstrings added for these changes

## Changes 

* Adds the DrugBank DDI and TwoSides Datasets.
* Adds the loaders.
* Adds tests.
* Adds documentation of data cleaning.
* Adds the data cleaning scripts.

### CODE REVIEW

**Comment by cthoyt** [comment]
I’d highly request provenance information on how these new datasets were constructed. Were they automatically downloaded from Some external repo? Was processing done to them?

**Comment by benedekrozemberczki** [comment]
Yes, @cthoyt I will do that in a moment.

**Comment by benedekrozemberczki** [comment]
There will be a whole Appendix section about this in the paper.

**Comment by cthoyt** [comment]
While you’re thinking about it maybe also consider doing the same for the previous two datasets as well :)

**Comment by benedekrozemberczki** [comment]
@cthoyt How about a dataset preprocessing section in the documentation?

**Comment by cthoyt** [comment]
Tbh the only important documentation of data preprocessing to me is code that can exactly reproduce it. Let’s start there and backfill prose-based documentation if there are any places where it can’t be better documented in code itself

**Comment by benedekrozemberczki** [comment]
Added the cleaning scripts.

**Comment by cthoyt** [comment]
It appears you merged the branch with failing tests. This shouldn’t be possible - the solution is to add some branch protection rules in the settings for the repository

**Comment by benedekrozemberczki** [comment]
Does it require changes to Github actions? 
Screenshot 2022-01-17 at 22 19 47

**Comment by cthoyt** [comment]
Nope that looks right!

**Pull request merged**
